In [ ]:
import torch
import pandas as pd
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[1, 2],
                      [3, 4]])

MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.size()

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

A brief note about tensors and their number of dimensions, and terminology:

* You will sometimes see a 1-dimensional tensor called a vector.

* Likewise, a 2-dimensional tensor is often referred to as a matrix.

* Anything with more than two dimensions is generally just called a tensor.


In [ ]:
empty = torch.empty(3, 4)
print(empty)
print("------")
print("Tensor Type is " ,type(empty))

tensor([[5.3679e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 1.1491e-43, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])
------
Tensor Type is  <class 'torch.Tensor'>


In [ ]:
zeros = torch.zeros(2, 3)
print(zeros)
zeros.dtype

ones = torch.ones(2, 3)
print(ones)
ones.dtype

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.float32

In [ ]:
# Random numbers

random = torch.rand(2, 3)
print(random)

tensor([[0.9556, 0.7036, 0.0625],
        [0.4860, 0.7843, 0.0026]])


In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
# Tensor Shape

x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[5.3682e-35, 0.0000e+00, 3.3631e-44],
         [0.0000e+00,        nan, 2.6170e-03]],

        [[4.4721e+21, 1.5956e+25, 4.7399e+16],
         [2.5607e-12, 1.6596e-07, 4.6952e-39]]])


In [ ]:
# torch.zeros_like(input) in our case the input is variable x
# Returns a tensor filled with the scalar value 0, with the same size as input

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0, 19.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.ndim

(torch.Size([4]), torch.float32, device(type='cpu'), 1)

In [ ]:
# basic math operations

x = torch.tensor([1, 2, 3])
y = x + 10
y

tensor([11, 12, 13])

In [ ]:
torch.mul(x, 10)

tensor([10, 20, 30])

In [ ]:
# Matrix Mul
# Note: "@" in Python is the symbol for matrix multiplication.

import torch
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor)

# You can also use torch.mm() which is a short for torch.matmul().


tensor(14)

In [ ]:
%%time 
tensor = torch.tensor([1, 2, 3])
torch.matmul(tensor, tensor)

CPU times: user 2.31 ms, sys: 0 ns, total: 2.31 ms
Wall time: 21.5 ms


tensor(14)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.6347, 0.8453, 0.4945],
        [0.4177, 0.1473, 0.2463],
        [0.3040, 0.4285, 0.2414]])

In [ ]:
# Transpose Matrix
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
tensor_A.T

tensor([[1., 3., 5.],
        [2., 4., 6.]])

In [ ]:
# Creating a range
zero_to_ten = torch.arange(0,10,1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create a tensor
some_tensor = torch.rand(3, 4)

# find out details about that tensor
print(some_tensor)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

tensor([[0.7012, 0.4250, 0.9748, 0.2673],
        [0.1733, 0.4912, 0.2162, 0.3760],
        [0.1415, 0.7946, 0.6746, 0.9829]])
torch.Size([3, 4])
torch.float32
cpu


In [ ]:
# create a linear layer

torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
# (3x2) @ (2x6)
output = linear(tensor_A)
print(f"Input Shape: {tensor_A.shape}\n")
print(f"Output:\n{output}\n\nOutput Shape: {output.shape}")

Input Shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output Shape: torch.Size([3, 6])


In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


In [ ]:
torch.max(x), torch.min(x), torch.sum(x)

(tensor(90), tensor(0), tensor(450))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Index Position
tensor = torch.arange(10,100,10)
print(tensor)

# return index of max and min values
print(tensor.argmax())
print(tensor.argmin())
# tensor[0] means give me the value in index 0

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(8)
tensor(0)


In [ ]:
# change data type

tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

Reshape Ref > https://deeplizard.com/learn/video/fCVuiW9AFzY

In [ ]:
# Reshape a tensor
a = torch.arange(4.)
print(a)
print(a.shape)
torch.reshape(a, (2,2))

tensor([0., 1., 2., 3.])
torch.Size([4])


tensor([[0., 1.],
        [2., 3.]])

In [ ]:
x = torch.arange(1, 9)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [ ]:
x_reshaped = x.reshape(1, 8)
x_reshaped, x_reshaped.shape

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
x_reshaped = x.reshape(4,2)
x_reshaped, x_reshaped.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]), torch.Size([4, 2]))

In [ ]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [ ]:
t.shape

torch.Size([3, 4])

In [ ]:
len(t.shape)

2

In [ ]:
# the number of elements contained within the tensor.
torch.tensor(t.shape).prod()

tensor(12)

In [ ]:
t.numel()

12

In [ ]:
t.reshape([1,12])

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [ ]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [ ]:
t.reshape([3,4])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [ ]:
# Change a view
# changing  z changes x, because they share the same memory

z = x.view(1, 7)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [ ]:
z[:, 0] = 5 
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7]]), tensor([5, 2, 3, 4, 5, 6, 7]))

In [ ]:
# Stack
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7]])

In [ ]:
# Squeeze, (I remember this as squeezing the tensor to only have dimensions over 1)

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7])
New shape: torch.Size([7])


In [ ]:
# Unsqueeze

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7])
Previous shape: torch.Size([7])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7]])
New shape: torch.Size([1, 7])


In [ ]:
import torch

In [ ]:
torch.rand(4)

tensor([0.0372, 0.1574, 0.3165, 0.1972])

In [ ]:
torch.randn(4)

tensor([ 3.4468,  0.7940,  1.6145, -0.8951])

In [ ]:
# torch.permute() - rearranges the dimensions of the a target tensor to a specified order, like images
# change images from HWC to CHW

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
# Indexing 

import torch

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x) 
print(f"\n{x.shape}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

torch.Size([1, 3, 3])


In [ ]:
x.ndim

3

In [ ]:
print(x[0]) # print the 1th dim (dim=0) the outer braket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
print([0][0]) # print the 2nd dim (dim=1) the middle braket
# print(x[0,0]) is the same

0


In [ ]:
print(x[0][1][1])

tensor(5)


In [ ]:
x[:,1] # print all dim 0 but only index 1 of the dim 1

tensor([[4, 5, 6]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# PyTorch and NumPy
# from NumPy to PyTorch > torch.from_numpy(ndarray)

import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype # default data type in numpy is float64

dtype('float64')

In [ ]:
# from PyTorch to NumPy > torch.Tensor.numpy()

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## PyTorch Reproducibility 

In [ ]:
import torch
import random

torch.manual_seed(42)
tensor_A = torch.rand(4, 3)

torch.manual_seed(42)
tensor_B = torch.rand(4, 3)

tensor_A == tensor_B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
# Run on GPU

!nvidia-smi

Tue Dec  6 05:39:11 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    31W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# access GPU with PyTorch

import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of devices

torch.cuda.device_count()

1

## Putting tensors/models on the GPU

Because using tensors on GPU is faster computations

In [ ]:
tensor = torch.tensor([1,2,3])
#tensor not on GPU
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# move tensor to GPU
# https://pytorch.org/docs/stable/generated/torch.Tensor.to.html

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# if tensor on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# to fix this issue, set it first to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])